# @name register
POST http://localhost:9096/v1/user/register HTTP/1.1
Content-Type: application/json

{
  "client_id": "client_id",
  "user_name": "danang",
  "password": "test"
}
###

# @name secure
POST http://localhost:9096/v1/secure HTTP/1.1
Authorization: Bearer YzUyY2ZhMjAtMjJmNy0zYzY1LTk3MDItMzk4MDJmZmJiNzRm
###

# @name password
POST http://localhost:9096/v1/oauth/token HTTP/1.1
Authorization: Basic client_id:client_secret
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=danang&password=test&scope=all
###

# @name refresh_token
POST http://localhost:9096/v1/oauth/token HTTP/1.1
Authorization: Basic client_id:client_secret
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&refresh_token=ZmFhMTVkZmUtNzRkZC01MmI4LTk5MjUtOGRiODY4OGQwYTdj
