CREATE TABLE IF NOT EXISTS oauth_clients(
	CREATE TABLE oauth_clients(
		id VARCHAR(255) NOT NULL PRIMARY KEY,
		secret VARCHAR(255) NOT NULL,
		domain VARCHAR(255) NOT NULL,
		data TEXT NOT NULL
	)
);
