CREATE TABLE IF NOT EXISTS oauth_users(
	CREATE TABLE users(
		id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
		client_id VARCHAR (225) NOT NULL,
		user_name VARCHAR (225) NOT NULL,
		password VARCHAR (225) NOT NULL,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)
);
